# Generated by Django 5.0.6 on 2024-05-15 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_formation_bande'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='backimage',
            field=models.FileField(blank=True, null=True, upload_to='formation/images/', verbose_name='Backimage'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='formation/details/', verbose_name='Fichier'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='formation/tutoriels/')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.formation')),
            ],
        ),
    ]
